### ISSUE TITLE
Click Agenda Icon Show Blank Page

### ISSUE THREAD

**Issue by Luoxcat** [haydenull/logseq-plugin-agenda#137]
![image](https://user-images.githubusercontent.com/5655054/195977532-097dbf6e-8fec-4183-8803-1bbaa3aa501d.png)
```
vendor.ea68255b.js:41 TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at Function.from (<anonymous>)
    at Dt (index.92ab6d48.js:245:15245)
    at gk (vendor.ea68255b.js:39:53145)
    at XW (vendor.ea68255b.js:43:8818)
    at WW (vendor.ea68255b.js:43:954)
    at $De (vendor.ea68255b.js:43:880)
    at cx (vendor.ea68255b.js:43:731)
    at Vk (vendor.ea68255b.js:41:10907)
    at Yf (vendor.ea68255b.js:41:8441)
    at Jw (vendor.ea68255b.js:43:15917)
index.92ab6d48.js:245 Uncaught (in promise) TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at Function.from (<anonymous>)
    at Dt (index.92ab6d48.js:245:15245)
    at gk (vendor.ea68255b.js:39:53145)
    at XW (vendor.ea68255b.js:43:8818)
    at WW (vendor.ea68255b.js:43:954)
    at $De (vendor.ea68255b.js:43:880)
    at cx (vendor.ea68255b.js:43:731)
    at Vk (vendor.ea68255b.js:41:10907)
    at Yf (vendor.ea68255b.js:41:8441)
    at Jw (vendor.ea68255b.js:43:15917)
```

**Comment by haydenull** [comment]
What is the version of logseq and the plugin version?
